spring.application.name=doncards

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/doncards
spring.datasource.username=duser
spring.datasource.password=password
