CREATE TABLE ENGLISH (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(400) NOT NULL
);

CREATE TABLE POLISH (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(400) NOT NULL
);

CREATE TABLE ENGLISH_POLISH (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    english_id BIGINT NOT NULL,
    polish_id BIGINT NOT NULL,
    FOREIGN KEY (english_id) REFERENCES ENGLISH(id),
    FOREIGN KEY (polish_id) REFERENCES POLISH(id)
);